/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-11-03 18:52:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.wy.domain.MemberForm;

public final class fg_002dTwo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      com.wy.dao.MemberDao dao = null;
      dao = (com.wy.dao.MemberDao) _jspx_page_context.getAttribute("dao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dao == null){
        dao = new com.wy.dao.MemberDao();
        _jspx_page_context.setAttribute("dao", dao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

request.setCharacterEncoding("GBK");
MemberForm form=dao.selectMemberForm(request.getParameter("name"));
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("<title>电子商城</title>\r\n");
      out.write("</head>\r\n");
      out.write(" <link href=\"css/css.css\" rel=\"stylesheet\" type=\"text/css\"> \r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function checkEmpty(form){\r\n");
      out.write("for(i=0;i<form.length;i++){\r\n");
      out.write("if(form.elements[i].value==\"\"){\r\n");
      out.write("alert(\"表单信息不能为空\");\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fg-top.jsp", out, true);
      out.write("\r\n");
      out.write("<table width=\"766\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#000000\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td bgcolor=\"#FFFFFF\" align=\"center\">\r\n");
      out.write("<img src=\"image/fg2.jpg\" width=\"752\" height=\"45\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    ");
if(form==null||form.equals("")){
      out.write("\r\n");
      out.write(" <p><strong>不存在此会员名称,请重新输入！！！</strong></p>\r\n");
      out.write(" <meta http-equiv=\"refresh\" content=\"3;URL=fg-One.jsp\">\r\n");
      out.write("  ");
}else{
      out.write("\r\n");
      out.write("  <p><strong>输入答案</strong></p>\r\n");
      out.write("  <form name=\"form\" method=\"post\" action=\"fg-three.jsp\" onSubmit=\"return checkEmpty(form)\">\r\n");
      out.write("    <table width=\"298\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bordercolor=\"#FFFFFF\" bordercolordark=\"#819BBC\" bordercolorlight=\"#FFFFFF\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"105\" height=\"35\">\r\n");
      out.write("          <div align=\"right\">问题:</div></td>\r\n");
      out.write("        <td width=\"187\"><div align=\"left\">\r\n");
      out.write("            <input type=\"hidden\" name=\"name\" value=\"");
      out.print(form.getName());
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"question\" value=\"");
      out.print(form.getQuestion());
      out.write("\">\r\n");
      out.write("            ");
      out.print(form.getQuestion());
      out.write("\r\n");
      out.write("        </div></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("        <td width=\"105\" height=\"35\">\r\n");
      out.write("          <div align=\"right\">答案:</div></td>\r\n");
      out.write("        <td width=\"187\">\r\n");
      out.write("          <div align=\"left\">\r\n");
      out.write("            <input type=\"text\" name=\"result\">\r\n");
      out.write("          </div></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <br>\r\n");
      out.write("     <input type=\"image\" class=\"input1\"  src=\"image/save.jpg\" width=\"51\" height=\"20\">\r\n");
      out.write("&nbsp;&nbsp;\r\n");
      out.write("      <a href=\"#\" onClick=\"javascript:form.reset()\"><img src=\"image/clear.gif\"></a>\r\n");
      out.write("&nbsp;&nbsp;\r\n");
      out.write("      <a href=\"#\" onClick=\"javasrcipt:history.go(-1)\"><img src=\"image/back.gif\"></a>\r\n");
      out.write("  </form>\r\n");
}
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("   </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fg-down.jsp", out, true);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
